# A human-readable name for your workflow
name: Run Neuro Bot

# --- TRIGGERS ---
# This section defines WHEN the workflow will run.
on:
  # 1. Allows you to manually start the workflow from the Actions tab.
  workflow_dispatch:

  # 2. (Optional but recommended) Automatically starts the workflow when you push code to the main branch.
  # You would still need to cancel the old run and let the new one proceed.
  push:
    branches: [ "main" ]

# --- JOBS ---
# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # We have one job called "run-bot"
  run-bot:
    # The type of virtual machine to run the job on. "ubuntu-latest" is the best choice.
    runs-on: ubuntu-latest

    # --- STEPS ---
    # A sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Checks out your repository's code so the job can access it.
      - name: Check out repository code
        uses: actions/checkout@v3

      # Step 2: Sets up a Python environment for you.
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install system dependencies needed for Chrome.
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xvfb

      # Step 4: Install Google Chrome browser itself.
      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f -y # Install any missing dependencies for Chrome

      # Step 5: Install the Python packages required by your script.
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy selenium requests fake-useragent psutil "urllib3<2"

      # Step 6: Run your Python script.
      # It uses the "env" block to securely pass your secrets as environment variables.
      - name: Run Neuro Bot Script
        env:
          FIREBASE_GMAIL_USER: ${{ secrets.FIREBASE_GMAIL_USER }}
          FIREBASE_GMAIL_APP_PASSWORD: ${{ secrets.FIREBASE_GMAIL_APP_PASSWORD }}
          HTTP_PROXIES_LIST: ${{ secrets.HTTP_PROXIES_LIST }}
        run: python neuro_bot_illusion_lite.py
