name: Run Bot

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true

    - name: Run script
      run: |
        python "Final version minions works gemeini buildt.py"
