# A human-readable name for your workflow
name: Run Neuro Bot

# --- CONCURRENCY ---
# This is the secret sauce. It ensures only ONE instance of this workflow runs at a time.
# If a new run is triggered (e.g., by the schedule), it will automatically cancel the previous run.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# --- TRIGGERS ---
# This section defines WHEN the workflow will run.
on:
  # 1. Allows you to manually start the workflow from the Actions tab.
  workflow_dispatch:

  # 2. Automatically starts the workflow every 6 hours.
  # It's like setting a recurring alarm clock for your bot.
  # `0 */6 * * *` means "at minute 0 of every 6th hour".
  schedule:
    - cron: '0 */6 * * *'

  # 3. (Optional but good to keep) Automatically starts on a push to main.
  push:
    branches: [ "main" ]

# --- JOBS ---
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xvfb

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f -y # Install any missing dependencies for Chrome

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy selenium requests fake-useragent psutil "urllib3<2"

      - name: Run Neuro Bot Script
        env:
          FIREBASE_GMAIL_USER: ${{ secrets.FIREBASE_GMAIL_USER }}
          FIREBASE_GMAIL_APP_PASSWORD: ${{ secrets.FIREBASE_GMAIL_APP_PASSWORD }}
        run: python "Final version minions works gemeini buildt.py"
